# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":atb"
    replace: "All the best,\nHayden Braxton"

  - trigger: ":workemail"
    replace: "hayden.braxton@flocksafety.com"

  - trigger: ":email"
    replace: "haydenbraxton@haydenbraxton.com"

  - trigger: ":user"
    replace: "hayden.braxton"

  - trigger: ":branch"
    replace: "hayden.braxton/CLOUD-"

  - trigger: ":newbranch"
    replace: "git checkout -b hayden.braxton/CLOUD-"

  - trigger: ":d.qs"
    replace: "document.querySelector('')"

  - trigger: ":getAccessToken"
    replace: "JSON.parse(localStorage.getItem('Auth__')).access_token"

  # quizlet 
  - trigger: ":informal"
    replace: "you (informal)"

  - trigger: ":formal"
    replace: "you (formal) / they"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
